### PR TITLE
Fixes for GPR#1200

### PR DESCRIPTION
**Pull request by dra27**
The headline change here is that this gives full CI pass on AppVeyor and I've also fully tested the six Windows ports on Windows Server 2016. The changes:

 - Merge artefact rebasing the `Changes` file (I also think the entry should really be under Runtime, rather than Standard Library)
 - Your rebase dropped your change to `Makefile.several` - it's a good change, even if not strictly related to this GPR. Similarly, I also did a little tidy-up of the "skipped" message. It's not yet merged, but the idea is that the total number of considered tests should always be the same no matter which platform or settings you have.
 - GCC complains about the implicit declaration of `win_wide_char_to_multi_byte` in systhreads (warning [C4013](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4013) isn't turned on for MSVC yet)

Commit https://github.com/dra27/ocaml/commit/75d8aa6cbbed508ec686e0b061c7148b3a73740d bothers me (I'd be grateful if @xavierleroy may be able to shed any light on this). The problem is twofold:
 1. The arrays passed in the execv family of functions in Posix are `char * const *` (see [1003.1-2008](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html)) but in MSDN are `const char * const *` (see [MSDN](https://docs.microsoft.com/en-gb/cpp/c-runtime-library/reference/execv-wexecv))
 2. Passing the `char **` from `cstringvect` has never caused problems, presumably anywhere. However, GCC does not seem happy to convert `wchar_t **` to `const wchar_t * const *` without a cast. It may of course be that MSVC is only happy because of our lower warning level.

The solution ends up being ugly, because we have to cater for the two different `const`nesses. In this implementation, I have assumed that Posix-based applications require no cast, just in case there are Unixes out there which also have `const char * const *` declarations.

However, I don't understand why the cast is only necessary for `wchar_t` and not `char` and I have a reputation for not liking fixes I don't understand 😞

### CODE REVIEW

**Comment by nojb** [comment]
Thanks @dra27 ! Can I merge this or is it dependent on some other PR for the changes in the testsuite makefiles ?

**Comment by dra27** [comment]
This can be merged straightaway if you're happy - there are some other review points in the main PR, but this gets us to the point of everything building!

**Comment by nojb** [comment]
Yes, indeed. I will make a list of those points that I am still not sure about and make a note in the main PR as well.

**Comment by xavierleroy** [comment]
I can't quite give a rational explanation of why `char **` to `const char * const *` is not a valid assignment, but I can say that GCC, Clang, and even CompCert agree on this.

**Pull request merged**
